version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase
    volumes:
      - .:/usr/src/app
    command: npm start

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
  
volumes:
  mongo_data: